package model;

public enum EventName {
    EVENT_100_METERS,
    EVENT_LONG_JUMP,
    EVENT_SHOT_PUT,
    EVENT_HIGH_JUMP,
    EVENT_400_METERS,
    EVENT_110_METERS_HURDLES,
    EVENT_DISCUS_THROW,
    EVENT_POLE_VAULT,
    EVENT_JAVELIN_THROW,
    EVENT_1500_METERS
}

